{
    "application":      "Aggregami",
    "copyright":        "&copy; Vightel, 2013",
    "contact":          "Pat Cappelaere",
    "contact_mail":     "pat@cappelaere.com",
    "hostBaseUrl":      "http://localhost:7464"
}

